name: "Sample react ci pipeline"

on:
  push:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: "Clone the repository"
        uses: actions/checkout@v4

      - name: "Setup Node JS"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: "Check node version"
        run: node -v

      - name: "List dir before installation"
        run: ls -la

      - name: "Install dependencies"
        run: npm ci

      - name: "List directories"
        run: ls -la

      - name: "Test"
        run: npm run test

      - name: "Lint"
        run: npm run lint

      - name: "Build"
        run: npm run build
